### ISSUE TITLE
Trello board link not found

### ISSUE THREAD

**Issue by bovas85** [artitudinale1/FCCLND#1]
Can you double check?

**Comment by artitudinale1** [comment]
Is this not working https://trello.com/b/wrbJkZPc/fcc-lnd-portal ?
Are you login in Trello?

**Comment by artitudinale1** [comment]
try https://trello.com/b/wrbJkZPc

**Comment by bovas85** [comment]
Yes I'm logged in but I get a board not found error.

**Comment by bovas85** [comment]
Did you set to public? My trello is Moustache Design

**Comment by artitudinale1** [comment]
Apologise ...it should be public now....

**Comment by artitudinale1** [comment]
https://trello.com/invite/b/wrbJkZPc/092572127ca9cb961de6657a6cdaca04/fcc-lnd-portal

**Comment by bovas85** [comment]
all good thanks :D
